In [1]:
#1
import numpy as np

num_list = [12.23, 13.32, 100, 36.32]
num_array = np.array(num_list)
print("Original List:", num_list)
print("One-dimensional numpy array:", num_array)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23  13.32 100.    36.32]


In [3]:
#2
import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
#3
import numpy as np
null_vector = np.zeros(10)
null_vector[6] = 11
print(null_vector)


[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
#4
import numpy as np

arr = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 
                27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
reversed_arr = arr[::-1]
print(reversed_arr)


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [6]:
#5
import numpy as np
array = np.zeros((5, 5))
array[1:-1, 1:-1] = 1  #rows,columns
print(array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#6
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#7
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill odd rows, even columns with 1
checkerboard[::2, 1::2] = 1  # Fill even rows, odd columns with 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
#8
import numpy as np

list_data = [1, 2, 3, 4, 5, 6, 7, 8]
tuple_data = ((8, 4, 6), (1, 2, 3))
# Convert to NumPy arrays
array_from_list = np.array(list_data)
array_from_tuple = np.array(tuple_data)
print("List to array:")
print(array_from_list)
print("\nTuple to array:")
print(array_from_tuple)


List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


In [11]:
#9
import numpy as np
list_data = [10,20,30]
appended_list= np.append(list_data,[40,50,60,70,80,90])
print(appended_list)

[10 20 30 40 50 60 70 80 90]


In [12]:
#10
import numpy as np
complex_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])
real_part = np.real(complex_array)
imaginary_part = np.imag(complex_array)
print("\nReal part of the array:")
print(real_part)
print("\nImaginary part of the array:")
print(imaginary_part)


Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


In [14]:
#11
import numpy as np
arr = np.array([10, 20, 30], dtype=np.int64)
size_of_array = arr.size
element_size = arr.itemsize   #size of 1 element
total_bytes = arr.nbytes #total bytes
print("Size of the array:", size_of_array)
print("Length of one array element in bytes:", element_size)
print("Total bytes consumed by the elements of the array:", total_bytes)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [15]:
#12
import numpy as np

arr1= np.array([0, 10, 20, 40, 60])
arr2= np.array([10, 30, 40])

res=np.intersect1d(arr1, arr2)
print(res)

[10 40]


In [16]:
#13
import numpy as np

arr1= np.array([0, 10, 20, 40, 60,80])
arr2= np.array([10, 30, 40, 50, 70, 90]) 

res=np.setdiff1d(arr1, arr2)
print(res)

[ 0 20 60 80]


In [17]:
#14
import numpy as np

arr1= np.array([0, 10, 20, 40, 60,80])
arr2= np.array([10, 30, 40, 50, 70, 90]) 

res=np.setxor1d(arr1, arr2)
print(res)

[ 0 20 30 50 60 70 80 90]


In [18]:
#15
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])


greater = a > b
greater_equal = a >= b
less = a < b
less_equal = a <= b

print("Array a:", a)
print("Array b:", b)
print("\na > b")
print(greater)
print("\na >= b")
print(greater_equal)
print("\na < b")
print(less)
print("\na <= b")
print(less_equal)

Array a: [1 2]
Array b: [4 5]

a > b
[False False]

a >= b
[False False]

a < b
[ True  True]

a <= b
[ True  True]


In [19]:
#15
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the array to a text file
np.savetxt("array.txt", arr, fmt="%d")

print("Array saved to 'array.txt' successfully!")


Array saved to 'array.txt' successfully!


In [20]:
#16
import numpy as np

original_array = np.array([[10, 20, 30], [20, 40, 50]])

new_flattened_arr=np.ravel(original_array)
print(new_flattened_arr)

[10 20 30 20 40 50]


In [25]:
#17
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], dtype=np.int64)
print("\nData type of the array x is:", x.dtype)

# Convert to float64
x_float = x.astype(np.float32)

print("\nNew Type:", x_float.dtype)
print(x_float)


Data type of the array x is: int64

New Type: float32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [26]:
#18
import numpy as np
# Create a 3x3 identity-like 3D array
array_3d = np.eye(3, dtype=float)
print(array_3d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#19
import numpy as np

arr1=np.zeros((4,3))
for i in range(1,4):
    for j in range(1,3):
        arr1[i][j]=1
print(arr1)


[[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]]


In [28]:
#20
import numpy as np
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])
result = np.concatenate((array1, array2), axis=1)

print(result)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [30]:
#21
import numpy as np

x = np.array([10, 20, 30, 40, 50])

# Make the array read-only
x.flags.writeable = False

# Test the array is read-only or not
print("Test the array is read-only or not:")

try:
    # Attempt to modify the first element
    x[0] = 1
except ValueError as e:
    print("Error:", e)  # Expected error: assignment destination is read-only


Test the array is read-only or not:
Error: assignment destination is read-only


In [31]:
#22
import numpy as np
array = np.arange(12).reshape(3, 4)
new_array = array * 3
print(new_array)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [32]:
#23
import numpy as np

a = np.array([[0, 1], [2, 3], [4, 5]])
new_list = a.tolist()

print(new_list)


[[0, 1], [2, 3], [4, 5]]


In [33]:
#24
import numpy as np


array = np.random.rand(10)


python_list = array.tolist()


np.set_printoptions(precision=3, suppress=True)
print("\nPrint array values with precision 3:")
print(array)



Print array values with precision 3:
[0.678 0.586 0.624 0.097 0.627 0.178 0.834 0.54  0.371 0.575]


In [34]:
#25
import numpy as np

# Create a NumPy array with small and large values
array = np.array([1.6e-10, 1.6, 1.2e+3, 2.35e-1])

print("Original array elements:")
print(array)

# Suppress scientific notation and print with precision 3
np.set_printoptions(precision=3, suppress=True)
print("\nPrint array values with precision 3:")
print(array)


Original array elements:
[   0.       1.6   1200.       0.235]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [35]:
#26
import numpy as np


array = np.array([[10, 20, 30], [40, 50, 60]])

# new column 
new_column = np.array([[100], [200]])

# Concatenate along axis=1 (columns)
new_array = np.hstack((array, new_column))

print(new_array)


[[ 10  20  30 100]
 [ 40  50  60 200]]


In [36]:
#27
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
to_delete = [0, 3, 4]

new_array = np.delete(array, to_delete)

print("\nDelete first, fourth and fifth elements:")
print(new_array)



Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
